#!/usr/bin/perl -Ilib

use strict;
use warnings;



=head1 NAME

[% package.name %] - [% package.desc %]

=head1 VERSION

Version 0.01

=head1 SYNOPSIS

Quick summary of what the module does.

Perhaps a little code snippet.

=head1 AUTHOR

[% author.name %], C<< [% author.email %] >>

=head1 BUGS

Please report any bugs or feature requests to C<< [% author.email %] >>



=head1 SUPPORT

You can find documentation for this module with the perldoc command.

    perldoc [% package.name %]


=back


=head1 ACKNOWLEDGEMENTS


=head1 COPYRIGHT & LICENSE

Copyright 2009 [% author.name %], [% author.company %], all rights reserved.

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.

=cut

